In [5]:
import pandas as pd

from data_processing.nkod_datasets import NKOD
import yaml

with open("config_experiments.yaml", "r") as f:
    config = yaml.safe_load(f)

config = config
dataset_portal = NKOD(config)
dataset_portal.load()
df = dataset_portal.super_df
df

2026-01-17 11:13:19 - data_processing.nkod_datasets - INFO - File exists
2026-01-17 11:13:19 - data_processing.nkod_datasets - INFO - Not modified today
2026-01-17 11:13:32 - data_processing.nkod_datasets - INFO - Downloading datove_sady.csv.
2026-01-17 11:13:40 - data_processing.nkod_datasets - INFO - Number of rows: 31011.
2026-01-17 11:13:40 - data_processing.nkod_datasets - INFO - Dataset info loaded.
2026-01-17 11:13:40 - data_processing.nkod_datasets - INFO - Loading extended NKOD dataset.

,datová_sada,název,popis,poskytovatel,periodicita_aktualizace,klíčová_slova,prostorové_pokrytí,téma,právní_předpis
0,https://data.gov.cz/zdroj/datové-sady/70889546...,ZOO a zooparky,Datová sada s prostorovou lokalizací zoologick...,Královéhradecký kraj,nepravidelný,"[Královéhradecký kraj, Zooparky, ZOO]",[https://linked.cuzk.cz/resource/ruian/vusc/86],"[Vzdělávání, kultura a sport]",[http://data.europa.eu/eli/dir/2019/1024/oj]
3,https://data.gov.cz/zdroj/datové-sady/70889546...,Významné oborové záměry ekonomického rozvoje v...,Vrstva ze Zásad územního rozvoje Královéhradec...,Královéhradecký kraj,nepravidelný,"[Významné oborové záměry ekonomického rozvoje,...",[https://linked.cuzk.cz/resource/ruian/vusc/86],"[Vláda a veřejný sektor, Regiony a města]",[http://data.europa.eu/eli/dir/2019/1024/oj]
9,https://data.gov.cz/zdroj/datové-sady/70889546...,Počet ubytovaných v domovech mládeže a interná...,Datová sada zobrazující počet ubytovaných v do...,Královéhradecký kraj,neznámý,"[Internáty, Domovy mládeže, Královéhradecký kr...",[https://linked.cuzk.cz/resource/ruian/vusc/86],"[Vzdělávání, kultura a sport, Věda a technika]",[http://data.europa.eu/eli/dir/2019/1024/oj]
17,https://data.gov.cz/zdroj/datové-sady/70889546...,Administrativní členění obcí,Datová sada s prostorovou lokalizací obcí na ú...,Královéhradecký kraj,nepravidelný,"[Regiony, Královéhradecký kraj, Členění, Hrani...",[https://linked.cuzk.cz/resource/ruian/vusc/86],"[Vláda a veřejný sektor, Regiony a města]",[http://data.europa.eu/eli/dir/2019/1024/oj]
27,https://data.gov.cz/zdroj/datové-sady/70889546...,Schválené individuální dotace do kraje v letec...,Datová sada s prostorovou lokalizací schválený...,Královéhradecký kraj,neznámý,"[Kraj, Dotace, Královéhradecký kraj, Individuá...",[https://linked.cuzk.cz/resource/ruian/vusc/86],"[Vláda a veřejný sektor, Regiony a města]",[http://data.europa.eu/eli/dir/2019/1024/oj]
...,...,...,...,...,...,...,...,...,...
259120,https://data.gov.cz/zdroj/datové-sady/00063584...,Úřední deska,Tato datová sada obsahuje data z úřední desky ...,Městská část Praha 4,denní,[úřední deska],[https://linked.cuzk.cz/resource/ruian/stat/1],[Vláda a veřejný sektor],[http://data.europa.eu/eli/dir/2019/1024/oj]
259121,https://data.gov.cz/zdroj/datové-sady/00241687...,Úřední deska,Tato datová sada obsahuje data z úřední desky ...,Městská část Praha 13,denní,[úřední deska],[https://linked.cuzk.cz/resource/ruian/momc/53...,[Vláda a veřejný sektor],[http://data.europa.eu/eli/dir/2019/1024/oj]
259122,https://data.gov.cz/zdroj/datové-sady/00837971...,Smlouvy Správy Národního parku Podyjí,Povinně zveřejňované smlouvy Správy Národního ...,Správa Národního parku Podyjí,týdenní,"[smlouvy, finance]",[https://linked.cuzk.cz/resource/ruian/stat/1],[Hospodářství a finance],[http://data.europa.eu/eli/dir/2019/1024/oj]
259124,https://data.gov.cz/zdroj/datové-sady/00837971...,Faktury Správy Národního parku Podyjí,Povinně zveřejňované faktury Správy Národního ...,Správa Národního parku Podyjí,týdenní,"[fakrury, finance]",[https://linked.cuzk.cz/resource/ruian/stat/1],[Hospodářství a finance],[http://data.europa.eu/eli/dir/2019/1024/oj]
259126,https://data.gov.cz/zdroj/datové-sady/00063754...,Faktury,Faktury Úřadu městské části Praha 7,Městská část Praha 7,roční,"[transparence, faktury]",[https://vdp.cuzk.cz/vdp/ruian/vusc/19],"[Předběžné údaje, výsledek hlasování]",[http://data.europa.eu/eli/dir/2019/1024/oj]

In [6]:
# get all unique themes
themes = df["téma"].explode().unique()
themes

array(['Vzdělávání, kultura a sport', 'Vláda a veřejný sektor',
       'Regiony a města', 'Věda a technika', 'Hospodářství a finance',
       'Předběžné údaje', 'Doprava', 'Životní prostředí',
       'Spravedlnost, právní systém a veřejná bezpečnost',
       'Populace a společnost', 'místní médium', 'novinka',
       'úřední dokument', 'Zdraví',
       'Zemědělství, rybolov, lesnictví a výživa', 'hospitalizace',
       'zdravotnická služba', 'zdravotnická technologie',
       'sociální služby', 'autobus', 'dopravní prostředek',
       'organizace dopravy', 'dopravní oblast', 'městská doprava',
       'vodní tok', 'povodeň', 'veřejná správa', 'správní celek',
       '52 ŽIVOTNÍ PROSTŘEDÍ', 'územní management', None,
       'elektronické publikování', 'veřejné finance', 'plnění rozpočtu',
       'rozpočtová politika', 'rozpočet kraje', 'kontrola rozpočtu',
       'slovník', 'Energie', 'nákladní doprava', 'pozemní doprava',
       'dopravní přestupek', 'silniční doprava', 'vozidlo',
       '5206 ekologická politika', '5211 přírodní prostředí',
       '5216 poškozování životního prostředí', 'urbanismus',
       'územní plánování', 'identifikační průkaz', 'cestovní pas',
       'katastr nemotivostí', 'místo přechodného pobytu', 'metadata',
       'otevřená data', 'katalog', 'místní orgány státní správy',
       'veřejná služba', 'pravomoc výkonné moci', 'územní samospráva',
       'regionální orgány státní správy', 'orgány veřejné správy',
       'správa věcí veřejných', 'samospráva', 'výkonný orgán',
       'výkonná moc', 'pravomoc instituce',
       'způsobilost k právním úkonům', 'dělení podle pohlaví',
       'telekomunikační technika', 'všeobecné zdravotní pojištění',
       'rodinný stav', 'regulace telekomunikací', 'mobilní aplikace',
       'krátkodobé financování', 'Moravskoslezský kraj', 'atlas',
       'podnik služeb', 'vývoz odpadu', 'odpad', 'školní jídelna',
       'soukromé školství', 'výchovně vzdělávací zařízení',
       'veřejné školství', 'školní vzdělávání', 'vzdělávání',
       'městská hromadná doprava', 'právní předpisy místní správy',
       'kolejové vozidlo', 'veřejná doprava', 'místní daň',
       'finance místních úřadů', 'městské komunikace', 'nemovitost',
       'silniční síť', 'stojatá voda', 'průmyslový pozemek', 'les',
       'zelená plocha', 'železniční síť', 'vlakové nádraží', 'bydlení',
       'železniční doprava', 'město', 'sport', 'volný čas',
       'cyklistická stezka', 'ochrana rostlinné říše', 'parkovací plocha',
       'regionální plánování', 'bydlení ve městě', 'architektura',
       'soutěž', 'zaměstnanci', 'maloobchodní cena',
       'telekomunikační politika', 'rozpočet', 'poštovní služba',
       'telekomunikace', 'správní rozhodnutí',
       'zdravotně postižený pracovník', 'univerzální služba',
       'správní řízení', 'odborná kvalifikace', 'televize',
       'zpřístupňování informací', '32 VZDĚLÁVÁNÍ A KOMUNIKACE',
       'obecní rozpočet', 'místní zastupitelstvo', 'fakturace',
       'pronájem nemovitosti', 'komunální odpad', 'organizace', 'plán',
       'státní zdravotní služba', 'prevence nemocí', 'rakovina',
       '2841 zdraví', 'organizace zdravotnictví', 'zdravotní systém',
       'porodnost', 'léčivý přípravek', 'očkování', 'epidemie',
       'infekční nemoc', 'mentální choroba', 'databáze',
       'zdraví veřejnosti', 'počítačová gramotnost',
       'kardiovaskulární onemocnění', 'zdravotní statistika', 'mateřství',
       'plodnost', 'úmrtnost', 'epidemiologie', 'nemoc', 'zdravotní péče',
       'převoz nemocných', 'výdaje na zdraví', 'zdravotní politika',
       'zdravotnická legislativa', 'klasifikace', 'kódování',
       'statistická nomenklatura', 'úraz', 'onemocnění cest dýchacích',
       'zdravotnické zařízení', 'endokrinní nemoc', 'vakcína',
       'oplodnění ve zkumavce', 'kožní nemoc', 'poptávka po zaměstnání',
       'pracovní vztahy', 'pracovní doba', 'nabídka zaměstnání',
       'školství', 'Česko', 'stavba', 'zprostředkovatelna práce',
       'politika zaměstnanosti EU', 'rozdělení podle věku',
       'zaměstnavatel', 'kultura', 'profesní příprava', 'stupeň vzdělání',
       'vytváření pracovních příležitostí', 'trh práce', 'popis práce',
       'hlídání dětí', 'bezpečnost při práci', 'mzdová politika',
       'umístění podniku', '40 PODNIKÁNÍ A HOSPODÁŘSKÁ SOUTĚŽ',
       'typ podniku', 'Kypr', 'předmět podnikání', 'mzdové tarify',
       'Lotyšsko', 'institucionální struktura', 'organizace školství',
       'vědecký výzkum', 'organizace výzkumu', 'výzkum', 'Rumunsko',
       'Estonsko', 'pokuta', 'administrativní kontrola', 'Finsko',
       'síť škol', 'zpráva', 'investiční projekt', 'ročenka',
       'informační středisko', 'pracovní nezpůsobilost',
       'administrativní členění', 'demografie', 'důchodový plán',
       'Mezinárodní otázky', 'důchodce', 'podmínky pro odchod do důchodu',
       'měsíční mzda', 'výkon rozhodnutí',
       'osoba samostatně výdělečně činná', 'penále', 'lékařský posudek',
       'zdravotní pojištění', 'vyhláška', 'sociální zabezpečení',
       'právo na informace', 'statistika', 'zdravotní průkaz',
       'zdravotně postižený člověk', 'pojišťovna', 'jednostopé vozidlo',
       'financování z veřejných prostředků', 'kvalita ovzduší',
       'geologie', 'důlní provoz', 'informace', 'informační systém',
       'mezinárodní vodní cesta', 'vnitrozemská vodní doprava',
       'vnitrozemská vodní cesta', 'mezinárodní doprava',
       'činnost orgánů', 'region', 'ministerstvo', 'dopravní nehoda',
       'nevládní organizace', 'evropská kulturní událost',
       'obchodní událost', 'sportovní událost', 'nakládání s odpadem',
       'skladování odpadu', 'zneškodňování odpadu',
       'ochrana spotřebitele', 'vztahy mezi institucemi', 'rozhodnutí',
       'zabavení věci', 'motorové palivo', 'fosilní palivo', 'palivo',
       'bezolovnatý benzin', 'benzin', 'dieselová nafta', 'zemní plyn',
       'spalovací plyny', 'plyn', 'organizační schéma', 'kulturní akce',
       'kemp', 'kulturní dědictví', 'přírodní rezervace ve městě',
       'stavební památky', 'mateřská škola', 'mezinárodní půjčka',
       'knižní průmysl', 'sportovní organizace', 'mezinárodní politika',
       'nerostné zdroje', 'kontrolní úřad', 'zákon',
       'smlouva na veřejnou zakázku', 'historie', 'výsledek hlasování',
       'zoologická zahrada'], dtype=object)

In [10]:
# get all keywords and their count
keywords = df["klíčová_slova"].explode()
keyword_counts = keywords.value_counts()
# store this to file
keyword_counts.to_csv("../data/keyword_counts.csv")
keyword_counts

klíčová_slova
Katalog otevřených dat                             9584
IS DTM                                             9584
Základní prostorová situace                        9584
prohlídky vozidel                                  9264
STK                                                6288
                                                   ...
vodní hospodářství voda provozní ukazatele            1
majetková evidence voda vodohospodářské objekty       1
vodohospodářský majetek                               1
zákazníci                                             1
ministerstvo obrany                                   1
Name: count, Length: 5068, dtype: int64

In [8]:
df_metadata = pd.read_csv("../data/datasets_with_metadata.csv")
df_metadata

,title,description,url,keywords,themes,provider,legal_regulations,categories,region,time_period
0,ZPS obec Dobruška,Veřejná stavová data ZPS - doprovodné informac...,https://data.gov.cz/zdroj/datové-sady/70889546...,"['Královéhradecký kraj', 'Základní prostorová ...","['Hospodářství a finance', 'Regiony a města']",Královéhradecký kraj,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Hospodářství a finance']","['Dobruška', 'Královéhradecký kraj']",['31.10.2025']
1,ZPS obec Liberk,Veřejná stavová data ZPS - podrobné body pro o...,https://data.gov.cz/zdroj/datové-sady/70889546...,"['Královéhradecký kraj', 'Základní prostorová ...","['Hospodářství a finance', 'Regiony a města']",Královéhradecký kraj,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Hospodářství a finance']","['Liberk', 'Královéhradecký kraj']",['31.10.2025']
2,ZPS obec Voděrady,Veřejná stavová data ZPS - doprovodné informac...,https://data.gov.cz/zdroj/datové-sady/70889546...,"['Královéhradecký kraj', 'Základní prostorová ...","['Hospodářství a finance', 'Regiony a města']",Královéhradecký kraj,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Hospodářství a finance']","['Voděrady', 'Královéhradecký kraj']",['31.10.2025']
3,ZPS obec Vysoké Veselí,Veřejná stavová data ZPS - polohopis pro obec:...,https://data.gov.cz/zdroj/datové-sady/70889546...,"['Královéhradecký kraj', 'Základní prostorová ...","['Hospodářství a finance', 'Regiony a města']",Královéhradecký kraj,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Hospodářství a finance']","['Vysoké Veselí', 'Královéhradecký kraj']",['31.10.2025']
4,ZPS obec Kosice,Veřejná stavová data ZPS - doprovodné informac...,https://data.gov.cz/zdroj/datové-sady/70889546...,"['Královéhradecký kraj', 'Základní prostorová ...","['Hospodářství a finance', 'Regiony a města']",Královéhradecký kraj,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Hospodářství a finance']",['Královéhradecký kraj'],['31.10.2025']
...,...,...,...,...,...,...,...,...,...,...
95,ZPS obec Skalice,Veřejná stavová data ZPS - polohopis pro obec:...,https://data.gov.cz/zdroj/datové-sady/70889546...,"['Královéhradecký kraj', 'Základní prostorová ...","['Hospodářství a finance', 'Regiony a města']",Královéhradecký kraj,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Hospodářství a finance']","['Skalice', 'Královéhradecký kraj']",['31.10.2025']
96,ZPS obec Sadová,Veřejná stavová data ZPS - polohopis pro obec:...,https://data.gov.cz/zdroj/datové-sady/70889546...,"['Královéhradecký kraj', 'Základní prostorová ...","['Hospodářství a finance', 'Regiony a města']",Královéhradecký kraj,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Hospodářství a finance']","['Sadová', 'Královéhradecký kraj']",['31.10.2025']
97,ZPS obec Chleny,Veřejná stavová data ZPS - doprovodné informac...,https://data.gov.cz/zdroj/datové-sady/70889546...,"['Královéhradecký kraj', 'Základní prostorová ...","['Hospodářství a finance', 'Regiony a města']",Královéhradecký kraj,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Hospodářství a finance']",['Královéhradecký kraj'],['31.10.2025']
98,ZPS obec Osice,Veřejná stavová data ZPS - polohopis pro obec:...,https://data.gov.cz/zdroj/datové-sady/70889546...,"['Královéhradecký kraj', 'Základní prostorová ...","['Hospodářství a finance', 'Regiony a města']",Královéhradecký kraj,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Hospodářství a finance']","['Osice', 'Královéhradecký kraj']",['31.10.2025']
99,ZPS obec Bříšťany,Veřejná stavová data ZPS - podrobné body pro o...,https://data.gov.cz/zdroj/datové-sady/70889546...,"['Královéhradecký kraj', 'Základní prostorová ...","['Hospodářství a finance', 'Regiony a města']",Královéhradecký kraj,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Hospodářství a finance']","['Bříšťany', 'Královéhradecký kraj']",['31.10.2025']

In [9]:
categories = df["kategorie_hvd_název"].explode().unique()
print(categories)
# count how many datasets have any category assigned - it is not none

count = df["kategorie_hvd_název"].notna().sum()
print(f"Number of datasets with category assigned: {count}")
# categories = df["kategorie_hvd_IRI"].explode().unique()
# print(categories)

# get df that has category assigned
df_with_category = df[df["kategorie_hvd_název"].notna()]
df_with_category

KeyError: 'kategorie_hvd_název'