# Datové sady
https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F17651921%2F0bfbeafc910512d988efe02f83601bf2

CSV soubor obsahující datové sady dostupné na data.gov.cz.

In [1]:
from datetime import datetime
import os
import pandas as pd
import requests

filename = "datove_sady.csv"
url = "https://data.gov.cz/soubor/datov%C3%A9-sady.csv"

def download_todays_file(url, filename):
    """Check if *filename* file exists and was last modified today - if not, download it again."""
    response = requests.get(url)
    if os.path.exists(filename):
        mod_time = os.path.getmtime(filename)
        mod_datetime = datetime.fromtimestamp(mod_time)
        today = datetime.today().date()
    if not os.path.exists(filename) or mod_datetime.date() != today:
        with open(filename, "wb") as f:
            f.write(response.content)

download_todays_file(url, filename)
data_df = pd.read_csv(filename, sep=",")
data_df.head()

/tmp/ipykernel_715060/3210824753.py:21: DtypeWarning: Columns (13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  data_df = pd.read_csv(filename, sep=",")

,datová_sada,název,popis,poskytovatel_IRI,poskytovatel,klíčová_slova,prostorové_pokrytí,téma_IRI,téma,periodicita_aktualizace_IRI,periodicita_aktualizace,je_součástí_IRI,právní_předpis,kategorie_hvd_IRI,kategorie_hvd_název
0,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Tetín,Veřejná stavová data ZPS - podrobné body pro o...,https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Královéhradecký kraj,Královéhradecký kraj,https://linked.cuzk.cz/resource/ruian/vusc/86,http://publications.europa.eu/resource/authori...,Hospodářství a finance,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN
1,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Tetín,Veřejná stavová data ZPS - podrobné body pro o...,https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Královéhradecký kraj,IS DTM,https://linked.cuzk.cz/resource/ruian/vusc/86,http://publications.europa.eu/resource/authori...,Hospodářství a finance,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN
2,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Tetín,Veřejná stavová data ZPS - podrobné body pro o...,https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Královéhradecký kraj,Katalog otevřených dat,https://linked.cuzk.cz/resource/ruian/vusc/86,http://publications.europa.eu/resource/authori...,Hospodářství a finance,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN
3,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Tetín,Veřejná stavová data ZPS - podrobné body pro o...,https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Královéhradecký kraj,Základní prostorová situace,https://linked.cuzk.cz/resource/ruian/vusc/86,http://publications.europa.eu/resource/authori...,Hospodářství a finance,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN
4,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Ohařice,Veřejná stavová data ZPS - polohopis pro obec:...,https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Královéhradecký kraj,Královéhradecký kraj,https://linked.cuzk.cz/resource/ruian/vusc/86,http://publications.europa.eu/resource/authori...,Hospodářství a finance,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN

 # Distribuce datových sad
 https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F17651921%2F3eb22170cc15d37fbd9cad552b2a0526

Informace o distribucích datasetů.

In [2]:
filename = "distribuce.csv"
url = "https://data.gov.cz/soubor/distribuce.csv"
download_todays_file(url, filename)

distribution_df = pd.read_csv(filename, sep=",")
distribution_df.head()

,datová_sada,distribuce,typ,název,autorskéDílo,databázeAutorskéDílo,zvláštníPrávoPořizovateleDatabáze,osobníÚdaje,přístupovéUrl,formátSouboru,mediaTypeSouboru,odkazNaSchémaSouboru,popisPřístupovéhoBoduSlužby,specifikaceSlužby
0,https://data.gov.cz/zdroj/datové-sady/70890692...,https://data.gov.cz/zdroj/datové-sady/70890692...,Soubor,Distribuce 1,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://data.gov.cz/podmínky-užití/není-autors...,https://data.gov.cz/podmínky-užití/není-chráně...,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://msk.krajdtm.cz/dmx-server/orders/19657...,ZIP,NaN,NaN,NaN,NaN
1,https://data.gov.cz/zdroj/datové-sady/70890692...,https://data.gov.cz/zdroj/datové-sady/70890692...,Soubor,Distribuce 1,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://data.gov.cz/podmínky-užití/není-autors...,https://data.gov.cz/podmínky-užití/není-chráně...,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://msk.krajdtm.cz/dmx-server/orders/19657...,ZIP,NaN,NaN,NaN,NaN
2,https://data.gov.cz/zdroj/datové-sady/70890692...,https://data.gov.cz/zdroj/datové-sady/70890692...,Soubor,Distribuce 1,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://data.gov.cz/podmínky-užití/není-autors...,https://data.gov.cz/podmínky-užití/není-chráně...,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://msk.krajdtm.cz/dmx-server/orders/19657...,ZIP,NaN,NaN,NaN,NaN
3,https://data.gov.cz/zdroj/datové-sady/70890692...,https://data.gov.cz/zdroj/datové-sady/70890692...,Soubor,Distribuce 1,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://data.gov.cz/podmínky-užití/není-autors...,https://data.gov.cz/podmínky-užití/není-chráně...,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://msk.krajdtm.cz/dmx-server/orders/19657...,ZIP,NaN,NaN,NaN,NaN
4,https://data.gov.cz/zdroj/datové-sady/70889546...,https://data.gov.cz/zdroj/datové-sady/70889546...,Soubor,Distribuce 1,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://data.gov.cz/podmínky-užití/není-autors...,https://data.gov.cz/podmínky-užití/není-chráně...,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://khk.krajdtm.cz/dmx-server/orders/15033...,ZIP,NaN,NaN,NaN,NaN

In [4]:
df = pd.read_csv("../data/golden/datove_sady_small.csv")
df

,datová_sada,název,popis,poskytovatel_IRI,poskytovatel,klíčová_slova,prostorové_pokrytí,téma_IRI,téma,periodicita_aktualizace_IRI,periodicita_aktualizace,je_součástí_IRI,právní_předpis,kategorie_hvd_IRI,kategorie_hvd_název
0,https://data.gov.cz/zdroj/datové-sady/00020699...,Aproximativní inventura emisí skleníkových plynů,Dle nařízení Evropského parlamentu a rady EU 2...,https://data.gov.cz/zdroj/poskytovatel/00020699,Český hydrometeorologický ústav,metan,http://publications.europa.eu/resource/authori...,http://publications.europa.eu/resource/authori...,Životní prostředí,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/reg_impl/2023/138/oj,http://data.europa.eu/bna/c_59e64dd4,Klima
1,https://data.gov.cz/zdroj/datové-sady/00020699...,Aproximativní inventura emisí skleníkových plynů,Dle nařízení Evropského parlamentu a rady EU 2...,https://data.gov.cz/zdroj/poskytovatel/00020699,Český hydrometeorologický ústav,metan,http://publications.europa.eu/resource/authori...,http://publications.europa.eu/resource/authori...,Životní prostředí,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,http://data.europa.eu/bna/c_59e64dd4,Klima
2,https://data.gov.cz/zdroj/datové-sady/00020699...,Aproximativní inventura emisí skleníkových plynů,Dle nařízení Evropského parlamentu a rady EU 2...,https://data.gov.cz/zdroj/poskytovatel/00020699,Český hydrometeorologický ústav,metan,https://linked.cuzk.cz/resource/ruian/stat/1,http://publications.europa.eu/resource/authori...,Životní prostředí,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/reg_impl/2023/138/oj,http://data.europa.eu/bna/c_59e64dd4,Klima
3,https://data.gov.cz/zdroj/datové-sady/00020699...,Aproximativní inventura emisí skleníkových plynů,Dle nařízení Evropského parlamentu a rady EU 2...,https://data.gov.cz/zdroj/poskytovatel/00020699,Český hydrometeorologický ústav,metan,https://linked.cuzk.cz/resource/ruian/stat/1,http://publications.europa.eu/resource/authori...,Životní prostředí,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,http://data.europa.eu/bna/c_59e64dd4,Klima
4,https://data.gov.cz/zdroj/datové-sady/00020699...,Aproximativní inventura emisí skleníkových plynů,Dle nařízení Evropského parlamentu a rady EU 2...,https://data.gov.cz/zdroj/poskytovatel/00020699,Český hydrometeorologický ústav,oxid dusný,http://publications.europa.eu/resource/authori...,http://publications.europa.eu/resource/authori...,Životní prostředí,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/reg_impl/2023/138/oj,http://data.europa.eu/bna/c_59e64dd4,Klima
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1340,https://data.gov.cz/zdroj/datové-sady/00025593...,Volba prezidenta 2018 - číselníky,"Obsahuje 5 číselníků: Číselník okresů, krajů a...",https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Český statistický úřad,číselníky,https://linked.cuzk.cz/resource/ruian/stat/1,http://publications.europa.eu/resource/authori...,Hospodářství a finance,http://publications.europa.eu/resource/authori...,nikdy,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN
1341,https://data.gov.cz/zdroj/datové-sady/00025593...,Volba prezidenta 2018 - číselníky,"Obsahuje 5 číselníků: Číselník okresů, krajů a...",https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Český statistický úřad,číselníky,https://linked.cuzk.cz/resource/ruian/stat/1,http://publications.europa.eu/resource/authori...,Vláda a veřejný sektor,http://publications.europa.eu/resource/authori...,nikdy,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN
1342,https://data.gov.cz/zdroj/datové-sady/00025593...,Volba prezidenta 2018 - číselníky,"Obsahuje 5 číselníků: Číselník okresů, krajů a...",https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Český statistický úřad,číselníky,https://linked.cuzk.cz/resource/ruian/stat/1,http://publications.europa.eu/resource/authori...,Populace a společnost,http://publications.europa.eu/resource/authori...,nikdy,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN
1343,https://data.gov.cz/zdroj/datové-sady/00025593...,Volba prezidenta republiky,NaN,https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Český statistický úřad,volby,https://linked.cuzk.cz/resource/ruian/stat/1,http://publications.europa.eu/resource/authori...,Populace a společnost,http://publications.europa.eu/resource/authori...,pětiletý,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN
1344,https://data.gov.cz/zdroj/datové-sady/00025593...,Volba prezidenta republiky,NaN,https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Český statistický úřad,prezident,https://linked.cuzk.cz/resource/ruian/stat/1,http://publications.europa.eu/resource/authori...,Populace a společnost,http://publications.europa.eu/resource/authori...,pětiletý,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN