In [2]:
import pandas as pd

from data_processing.nkod_datasets import NKOD
import yaml

with open("config_experiments.yaml", "r") as f:
    config = yaml.safe_load(f)

config = config
dataset_portal = NKOD(config)
df = dataset_portal.super_df
df

2025-12-30 19:02:40 - data_processing.nkod_datasets - INFO - File exists
2025-12-30 19:02:40 - data_processing.nkod_datasets - INFO - File is up to date, loading from disk.
2025-12-30 19:02:46 - data_processing.nkod_datasets - INFO - Number of rows: 31642.
2025-12-30 19:02:46 - data_processing.nkod_datasets - INFO - Dataset info loaded.
2025-12-30 19:02:46 - data_processing.nkod_datasets - WARNING - Extended NKOD dataset file not found.

,datová_sada,název,popis,poskytovatel,periodicita_aktualizace,klíčová_slova,prostorové_pokrytí,téma,právní_předpis,kategorie_hvd_název
0,https://data.gov.cz/zdroj/datové-sady/70889546...,Zdroje dat na portálu,"Podívejte se, odkud odkud čerpáme data pro dat...",Královéhradecký kraj,neznámý,None,[https://linked.cuzk.cz/resource/ruian/vusc/86],[Předběžné údaje],[http://data.europa.eu/eli/dir/2019/1024/oj],None
1,https://data.gov.cz/zdroj/datové-sady/70889546...,O webu Data KHK,Informace o webu Data KHK a přehled jeho návšt...,Královéhradecký kraj,neznámý,None,[https://linked.cuzk.cz/resource/ruian/vusc/86],[Předběžné údaje],[http://data.europa.eu/eli/dir/2019/1024/oj],None
2,https://data.gov.cz/zdroj/datové-sady/70889546...,Památkové zóny,Datová sada s prostorovou lokalizací památkový...,Královéhradecký kraj,nepravidelný,"[Památkové zóny, Památky, Královéhradecký kraj]",[https://linked.cuzk.cz/resource/ruian/vusc/86],"[Vzdělávání, kultura a sport]",[http://data.europa.eu/eli/dir/2019/1024/oj],None
5,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Židovice,Veřejná stavová data ZPS - polohopis pro obec:...,Královéhradecký kraj,roční,"[Katalog otevřených dat, Základní prostorová s...",[https://linked.cuzk.cz/resource/ruian/vusc/86],[Hospodářství a finance],[http://data.europa.eu/eli/dir/2019/1024/oj],None
9,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Jasenná,Veřejná stavová data ZPS - doprovodné informac...,Královéhradecký kraj,roční,"[Katalog otevřených dat, Základní prostorová s...",[https://linked.cuzk.cz/resource/ruian/vusc/86],[Hospodářství a finance],[http://data.europa.eu/eli/dir/2019/1024/oj],None
...,...,...,...,...,...,...,...,...,...,...
261972,https://data.gov.cz/zdroj/datové-sady/00282481...,Úřední deska Rosice,Tato datová sada obsahuje data z úředních dese...,Město Rosice,denní,[úřední deska],"[https://linked.cuzk.cz/resource/ruian/stat/1,...","[úřední dokument, Vláda a veřejný sektor]",[http://data.europa.eu/eli/dir/2019/1024/oj],None
261978,https://data.gov.cz/zdroj/datové-sady/00257966...,Úřední deska města Kralovice,Datová sada obsahuje dokumenty úřední desky mě...,Město Kralovice,denní,[Úřední deska Kralovice],[https://linked.cuzk.cz/resource/ruian/orp/639...,"[úřední dokument, Vláda a veřejný sektor, Regi...",[http://data.europa.eu/eli/dir/2019/1024/oj],None
261984,https://data.gov.cz/zdroj/datové-sady/00284378...,Úřední deska Provodov,Tato datová sada obsahuje data z úředních dese...,OBEC PROVODOV,denní,[úřední deska],"[https://linked.cuzk.cz/resource/ruian/stat/1,...","[úřední dokument, Vláda a veřejný sektor]",[http://data.europa.eu/eli/dir/2019/1024/oj],None
261990,https://data.gov.cz/zdroj/datové-sady/00283924...,Úřední deska města Zlín,Tato datová sada obsahuje data z úřední desky ...,Statutární město Zlín,denní,[úřední deska],[https://linked.cuzk.cz/resource/ruian/pou/2933],[Vláda a veřejný sektor],[http://data.europa.eu/eli/dir/2019/1024/oj],None
261991,https://data.gov.cz/zdroj/datové-sady/48135267...,Úřední deska ÚNMZ,Obsah úřední desky Úřadu pro technickou normal...,"Úřad pro technickou normalizaci, metrologii a ...",denní,[úřední deska],[https://linked.cuzk.cz/resource/ruian/stat/1],[Vláda a veřejný sektor],[http://data.europa.eu/eli/dir/2019/1024/oj],None

In [3]:
# get all unique themes
themes = df["téma"].explode().unique()
themes

array(['Předběžné údaje', 'Vzdělávání, kultura a sport',
       'Hospodářství a finance', 'Doprava', 'Vláda a veřejný sektor',
       'Regiony a města', 'Věda a technika', 'Zdraví',
       'Životní prostředí',
       'Spravedlnost, právní systém a veřejná bezpečnost',
       'úřední dokument', 'novinka', 'místní médium',
       'Populace a společnost',
       'Zemědělství, rybolov, lesnictví a výživa', 'autobus',
       'dopravní prostředek', 'městská doprava',
       'zdravotnická technologie', 'zdravotnická služba', 'hospitalizace',
       'veřejná správa', 'organizace dopravy', 'sociální služby',
       'vodní tok', 'povodeň', 'dopravní oblast', 'správní celek',
       'územní management', '52 ŽIVOTNÍ PROSTŘEDÍ', None,
       'veřejné finance', 'rozpočet kraje', 'plnění rozpočtu',
       'rozpočtová politika', 'kontrola rozpočtu',
       'elektronické publikování', 'nákladní doprava', 'silniční doprava',
       'dopravní přestupek', 'pozemní doprava', 'vozidlo', 'Energie',
       'slovník', 'Moravskoslezský kraj', 'městská hromadná doprava',
       'železniční doprava', 'železniční síť',
       'právní předpisy místní správy', 'městské komunikace',
       'silniční síť', 'zelená plocha', 'vlakové nádraží',
       'průmyslový pozemek', 'stojatá voda', 'bydlení', 'les',
       'nemovitost', 'město', 'školní vzdělávání', 'vzdělávání',
       'výchovně vzdělávací zařízení', 'soukromé školství',
       'veřejné školství', 'finance místních úřadů', 'místní daň',
       'atlas', 'vývoz odpadu', 'odpad', 'podnik služeb',
       'bydlení ve městě', 'soutěž', 'architektura', 'kolejové vozidlo',
       'veřejná doprava', 'regionální plánování', 'volný čas',
       'cyklistická stezka', 'sport', 'ochrana rostlinné říše',
       'katastr nemotivostí', 'parkovací plocha', 'školní jídelna',
       'urbanismus', 'místní zastupitelstvo', 'fakturace',
       'obecní rozpočet', 'pronájem nemovitosti', 'organizace',
       'komunální odpad', 'plán', 'krátkodobé financování',
       'rodinný stav', 'regulace telekomunikací', 'dělení podle pohlaví',
       'místo přechodného pobytu', 'správa věcí veřejných',
       'místní orgány státní správy', 'regionální orgány státní správy',
       'pravomoc instituce', 'orgány veřejné správy',
       'pravomoc výkonné moci', 'veřejná služba', 'výkonná moc',
       'samospráva', 'výkonný orgán', 'územní samospráva',
       'telekomunikační technika', 'identifikační průkaz', 'cestovní pas',
       'všeobecné zdravotní pojištění', 'způsobilost k právním úkonům',
       'katalog', 'metadata', 'otevřená data', 'mobilní aplikace',
       'porodnost', 'mateřství', 'plodnost', 'státní zdravotní služba',
       'zdravotní statistika', 'převoz nemocných', 'prevence nemocí',
       'rakovina', 'léčivý přípravek', 'epidemie',
       'kardiovaskulární onemocnění', 'úraz', 'zdravotní péče', 'nemoc',
       'očkování', 'klasifikace', 'statistická nomenklatura', 'kódování',
       'infekční nemoc', 'počítačová gramotnost',
       'zpřístupňování informací', 'zdraví veřejnosti', '2841 zdraví',
       'organizace zdravotnictví', 'databáze', 'úmrtnost',
       'zdravotní systém', 'zdravotní politika', 'výdaje na zdraví',
       'zdravotnická legislativa', 'vakcína', 'mentální choroba',
       'onemocnění cest dýchacích', 'oplodnění ve zkumavce',
       'zdravotnické zařízení', 'epidemiologie', 'kožní nemoc',
       'endokrinní nemoc', 'správní rozhodnutí', 'zaměstnanci',
       'poštovní služba', 'maloobchodní cena', 'telekomunikační politika',
       'správní řízení', 'univerzální služba',
       'zdravotně postižený pracovník', 'rozpočet', 'televize',
       'odborná kvalifikace', '32 VZDĚLÁVÁNÍ A KOMUNIKACE', 'geologie',
       'důlní provoz', '40 PODNIKÁNÍ A HOSPODÁŘSKÁ SOUTĚŽ',
       'předmět podnikání', 'umístění podniku', 'typ podniku', 'Lotyšsko',
       'Estonsko', 'vědecký výzkum', 'organizace výzkumu', 'výzkum',
       'organizace školství', 'institucionální struktura',
       'administrativní kontrola', 'pokuta', 'Finsko', 'mzdové tarify',
       'Kypr', 'Rumunsko', 'investiční projekt', 'zpráva', 'ročenka',
       'síť škol', 'výsledek hlasování', 'rozhodnutí', 'palivo', 'benzin',
       'plyn', 'bezolovnatý benzin', 'dieselová nafta', 'motorové palivo',
       'zemní plyn', 'spalovací plyny', 'fosilní palivo', 'zabavení věci',
       'informace', 'ochrana spotřebitele', 'organizační schéma',
       'vztahy mezi institucemi', 'nabídka zaměstnání', 'region',
       'administrativní členění', 'nevládní organizace',
       'dopravní nehoda', 'ministerstvo', 'činnost orgánů',
       'mezinárodní politika', 'Mezinárodní otázky', 'kontrolní úřad',
       'smlouva na veřejnou zakázku', 'zákon', 'zneškodňování odpadu',
       'nakládání s odpadem', 'skladování odpadu', 'sportovní událost',
       'kultura', 'evropská kulturní událost', 'obchodní událost',
       'vnitrozemská vodní cesta', 'mezinárodní vodní cesta',
       'vnitrozemská vodní doprava', 'informační systém',
       'mezinárodní doprava', 'knižní průmysl', 'mezinárodní půjčka',
       'stavební památky', 'kulturní dědictví',
       'přírodní rezervace ve městě', 'kemp', 'sportovní organizace',
       'mateřská škola', 'kulturní akce', 'pojišťovna',
       'zdravotní pojištění', 'důchodce', 'důchodový plán',
       'výkon rozhodnutí', 'osoba samostatně výdělečně činná',
       'podmínky pro odchod do důchodu', 'lékařský posudek',
       'pracovní nezpůsobilost', 'vyhláška', 'sociální zabezpečení',
       'demografie', 'informační středisko', 'zaměstnavatel',
       'statistika', 'právo na informace', 'zdravotní průkaz',
       'zdravotně postižený člověk', 'měsíční mzda', 'penále',
       'zprostředkovatelna práce', 'trh práce', 'popis práce',
       'hlídání dětí', 'bezpečnost při práci', 'školství', 'Česko',
       'vytváření pracovních příležitostí', 'poptávka po zaměstnání',
       'mzdová politika', 'profesní příprava', 'pracovní vztahy',
       'pracovní doba', 'stavba', 'politika zaměstnanosti EU',
       'rozdělení podle věku', 'stupeň vzdělání', 'nerostné zdroje',
       'historie', 'jednostopé vozidlo',
       'financování z veřejných prostředků', 'kvalita ovzduší',
       'zoologická zahrada'], dtype=object)

In [4]:
keywords = df["klíčová_slova"].explode().unique()
print(keywords)

[None 'Památkové zóny' 'Památky' ... 'Kravaře'
 'Magistrát města Karlovy Vary' 'Úřední deska Kralovice']

In [7]:
categories = df["kategorie_hvd_název"].explode().unique()
print(categories)

[None 'Využití území' 'Zaměstnanost' 'Běžné výdaje na zdravotní péči'
 'Environmentální účty a statistické údaje'
 'Národní účty – hlavní souhrnné ukazatele HDP'
 'Členění indexu cen průmyslových výrobců podle činnosti'
 'Objem prodeje podle činnosti' 'Plodnost' 'Chudoba'
 'Statistika mezinárodního obchodu EU se zbožím – vývoz a dovoz, členění zároveň podle partnerů, výrobků a toků'
 'Populace' 'Úmrtnost' 'Toky cestovního ruchu v Evropě'
 'Výdaje a příjmy vládních institucí'
 'Harmonizované indexy spotřebitelských cen' 'Statistika'
 'Průmyslová výroba' 'Nezaměstnanost' 'Referenční pozemky'
 'Zemědělské pozemky' 'Vodopis' 'Dopravní sítě' 'Ortofotosnímky' 'Budovy'
 'Nadmořská výška' 'Zeměpisné názvy' 'Katastrální parcely' 'Adresy'
 'Správní jednotky' 'Krajinný pokryv' 'Výrobní a průmyslová zařízení'
 'Údaje z modelu numerických předpovědí počasí' 'Radarové údaje' 'Vzduch'
 'Emise' 'Klima' 'Odpad'
 'Údaje z pozorování naměřené v meteorologických stanicích'
 'Zařízení pro sledování životního prostředí' 'Meteorologická upozornění'
 'Klimatické údaje: ověřená pozorování' 'Chráněná území' 'Rozložení druhů'
 'Stanoviště a biotopy' 'Bioregiony' 'Geologie' 'Nerostné suroviny' 'Půda'
 'Energetické zdroje' 'Oblasti ohrožené přírodními riziky'
 'Správní oblasti / chráněná pásma / regulovaná území a jednotky podávající hlášení'
 'Voda' 'Mobilita']

In [6]:
df_metadata = pd.read_csv("../data/datasets_with_metadata.csv")
df_metadata

,title,description,url,keywords,themes,provider,legal_regulations,categories,domain,region,time_period
0,Aproximativní inventura emisí skleníkových plynů,Dle nařízení Evropského parlamentu a rady EU 2...,https://data.gov.cz/zdroj/datové-sady/00020699...,"['Stav ovzduší', 'oxid dusný', 'metan', 'oxidy...",['Životní prostředí'],Český hydrometeorologický ústav,"['http://data.europa.eu/eli/dir/2019/1024/oj',...",['Klima'],['Environment'],['-'],"['2024', '2023', '2025']"
1,Mapa normálu úhrnu doby trvání slunečního svit...,Mapa normálu úhrnu doby trvání slunečního svit...,https://data.gov.cz/zdroj/datové-sady/00020699...,"['Zeměpisné meteorologické prvky', 'ČHMÚ', 'no...",['Životní prostředí'],Český hydrometeorologický ústav,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,"['Environment', 'Geography']",['-'],"['1991', '1992', '1993', '1994', '1995', '1996..."
2,Mapa normálu úhrnu doby trvání slunečního svit...,Mapa normálu úhrnu doby trvání slunečního svit...,https://data.gov.cz/zdroj/datové-sady/00020699...,"['Stav ovzduší', 'Zeměpisné meteorologické prv...",['Životní prostředí'],Český hydrometeorologický ústav,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,"['Environment', 'Geography']",['-'],"['1991', '2020', '1991–2020']"
3,Stavební uzávěry,Stavební uzávěry vyplývající z vyhlášek hl. m....,https://data.gov.cz/zdroj/datové-sady/70883858...,NaN,['Regiony a města'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,['Infrastructure'],"['hlavní město Praha', 'Libeň', 'Čimice']",['-']
4,Stanoviště tříděného odpadu,Stanoviště tříděného odpadu. Tato stanoviště m...,https://data.gov.cz/zdroj/datové-sady/70883858...,NaN,['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,['Environment'],['-'],['-']
5,Protipovodňová ochrana,Objekt (zařízení) protipovodňové ochrany zápla...,https://data.gov.cz/zdroj/datové-sady/70883858...,NaN,['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,"['Environment', 'Infrastructure']","['Vltava', 'Berounka']",['-']
6,Protihlukové valy,Protihlukové valy mají charakter sypaného zemn...,https://data.gov.cz/zdroj/datové-sady/70883858...,NaN,['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,['Environment'],['-'],['-']
7,Pošty,Bodová vrstva obsahuje data o poštách a ostatn...,https://data.gov.cz/zdroj/datové-sady/70883858...,NaN,['Hospodářství a finance'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,"['Geography', 'Infrastructure']",['-'],['-']
8,"PoskytovatelZookoutky Lesů HMP a dále farmy, t...",Veřejně přístupné (v rámci provozní doby areál...,https://data.gov.cz/zdroj/datové-sady/70883858...,NaN,['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,['Environment'],['Prague'],['2024']
9,Veřejné zakázky příspěvkových organizací MHMP,Data o zadaných a ukončených veřejných zakázká...,https://data.gov.cz/zdroj/datové-sady/02795281...,NaN,"['financování z veřejných prostředků', 'Hospod...","Operátor ICT, a.s.",['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,"['Economics', 'Business']",['Prague'],['-']
10,Aproximativní inventura emisí skleníkových plynů,Dle nařízení Evropského parlamentu a rady EU 2...,https://data.gov.cz/zdroj/datové-sady/00020699...,"['oxid dusný', 'Národní', 'metan', 'Stav ovzdu...",['Životní prostředí'],Český hydrometeorologický ústav,['http://data.europa.eu/eli/reg_impl/2023/138/...,['Klima'],['Environment'],['-'],"['2024', '2023', '2025']"
11,Mapa normálu úhrnu doby trvání slunečního svit...,Mapa normálu úhrnu doby trvání slunečního svit...,https://data.gov.cz/zdroj/datové-sady/00020699...,"['Zeměpisné meteorologické prvky', 'ČHMÚ', 'no...",['Životní prostředí'],Český hydrometeorologický ústav,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,"['Environment', 'Geography']",['-'],"['1991', '2020', '1991–2020']"
12,Mapa normálu úhrnu doby trvání slunečního svit...,Mapa normálu úhrnu doby trvání slunečního svit...,https://data.gov.cz/zdroj/datové-sady/00020699...,"['klima', 'Zeměpisné meteorologické prvky', 'Č...",['Životní prostředí'],Český hydrometeorologický ústav,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,"['Environment', 'Geography']",['-'],"['1991', '2020', '1991–2020']"
13,Stavební uzávěry,Stavební uzávěry vyplývající z vyhlášek hl. m....,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Urbanismus/Urban planning', 'Urbanismus/Urba...",['Regiony a města'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,['Infrastructure'],['Prague'],['-']
14,Stanoviště tříděného odpadu,Stanoviště tříděného odpadu. Tato stanoviště m...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Odpady/Waste', 'Odpady', 'třídění']",['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,['Environment'],['-'],['-']
15,Protipovodňová ochrana,Objekt (zařízení) protipovodňové ochrany zápla...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Záplavy', 'Technická infrastruktura/Infrastr...",['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,"['Environment', 'Infrastructure']","['Vltava', 'Berounka']",['-']
16,Protihlukové valy,Protihlukové valy mají charakter sypaného zemn...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Hluk/Noise', 'Protihlukové valy', 'Ochrana h...",['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,['Environment'],['-'],['-']
17,Pošty,Bodová vrstva obsahuje data o poštách a ostatn...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Využití území', 'Urbanismus/Urban planning',...",['Hospodářství a finance'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,"['Economics', 'Infrastructure']",['-'],['-']
18,"PoskytovatelZookoutky Lesů HMP a dále farmy, t...",Veřejně přístupné (v rámci provozní doby areál...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Ochrana přírody/Nature conservation', 'zooko...",['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,['Environment'],['Prague'],['2024']
19,Veřejné zakázky příspěvkových organizací MHMP,Data o zadaných a ukončených veřejných zakázká...,https://data.gov.cz/zdroj/datové-sady/02795281...,"[' ', 'veřejné zakázky', 'veřejné zakázky', 'f...","['Hospodářství a finance', 'financování z veře...","Operátor ICT, a.s.",['http://data.europa.eu/eli/dir/2019/1024/oj'],NaN,"['Economics', 'Business']",['Prague'],['-']