# Datové sady
https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F17651921%2F0bfbeafc910512d988efe02f83601bf2

CSV soubor obsahující datové sady dostupné na data.gov.cz.

In [6]:
from datetime import datetime
import os
import pandas as pd
import requests

filename = "datove_sady.csv"
url = "https://data.gov.cz/soubor/datov%C3%A9-sady.csv"

def download_todays_file(url, filename):
    """Check if *filename* file exists and was last modified today - if not, download it again."""
    response = requests.get(url)
    if os.path.exists(filename):
        mod_time = os.path.getmtime(filename)
        mod_datetime = datetime.fromtimestamp(mod_time)
        today = datetime.today().date()
    if not os.path.exists(filename) or mod_datetime.date() != today:
        with open(filename, "wb") as f:
            f.write(response.content)

download_todays_file(url, filename)
data_df = pd.read_csv(filename, sep=",")
data_df.head()

,datová_sada,název,popis,poskytovatel_IRI,poskytovatel,klíčová_slova,prostorové_pokrytí,téma_IRI,téma,periodicita_aktualizace_IRI,periodicita_aktualizace,je_součástí_IRI,právní_předpis,kategorie_hvd_IRI,kategorie_hvd_název
0,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Borovnice,Veřejná stavová data ZPS - odvozené plošné typ...,https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Královéhradecký kraj,Královéhradecký kraj,https://linked.cuzk.cz/resource/ruian/vusc/86,http://publications.europa.eu/resource/authori...,Hospodářství a finance,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN
1,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Borovnice,Veřejná stavová data ZPS - odvozené plošné typ...,https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Královéhradecký kraj,IS DTM,https://linked.cuzk.cz/resource/ruian/vusc/86,http://publications.europa.eu/resource/authori...,Hospodářství a finance,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN
2,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Borovnice,Veřejná stavová data ZPS - odvozené plošné typ...,https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Královéhradecký kraj,Katalog otevřených dat,https://linked.cuzk.cz/resource/ruian/vusc/86,http://publications.europa.eu/resource/authori...,Hospodářství a finance,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN
3,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Borovnice,Veřejná stavová data ZPS - odvozené plošné typ...,https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Královéhradecký kraj,Základní prostorová situace,https://linked.cuzk.cz/resource/ruian/vusc/86,http://publications.europa.eu/resource/authori...,Hospodářství a finance,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN
4,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Chotěvice,Veřejná stavová data ZPS - polohopis pro obec:...,https://rpp-opendata.egon.gov.cz/odrpp/zdroj/o...,Královéhradecký kraj,Královéhradecký kraj,https://linked.cuzk.cz/resource/ruian/vusc/86,http://publications.europa.eu/resource/authori...,Hospodářství a finance,http://publications.europa.eu/resource/authori...,roční,NaN,http://data.europa.eu/eli/dir/2019/1024/oj,NaN,NaN

 # Distribuce datových sad
 https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F17651921%2F3eb22170cc15d37fbd9cad552b2a0526

Informace o distribucích datasetů.

In [7]:
filename = "distribuce.csv"
url = "https://data.gov.cz/soubor/distribuce.csv"
download_todays_file(url, filename)

distribution_df = pd.read_csv(filename, sep=",")
distribution_df.head()

,datová_sada,distribuce,typ,název,autorskéDílo,databázeAutorskéDílo,zvláštníPrávoPořizovateleDatabáze,osobníÚdaje,přístupovéUrl,formátSouboru,mediaTypeSouboru,odkazNaSchémaSouboru,popisPřístupovéhoBoduSlužby,specifikaceSlužby
0,https://data.gov.cz/zdroj/datové-sady/70890749...,https://data.gov.cz/zdroj/datové-sady/70890749...,Soubor,Distribuce 1,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://data.gov.cz/podmínky-užití/není-autors...,https://data.gov.cz/podmínky-užití/není-chráně...,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://vys.krajdtm.cz/dmx-server/orders/14205...,ZIP,NaN,NaN,NaN,NaN
1,https://data.gov.cz/zdroj/datové-sady/70890749...,https://data.gov.cz/zdroj/datové-sady/70890749...,Soubor,Distribuce 1,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://data.gov.cz/podmínky-užití/není-autors...,https://data.gov.cz/podmínky-užití/není-chráně...,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://vys.krajdtm.cz/dmx-server/orders/14205...,ZIP,NaN,NaN,NaN,NaN
2,https://data.gov.cz/zdroj/datové-sady/70890749...,https://data.gov.cz/zdroj/datové-sady/70890749...,Soubor,Distribuce 1,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://data.gov.cz/podmínky-užití/není-autors...,https://data.gov.cz/podmínky-užití/není-chráně...,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://vys.krajdtm.cz/dmx-server/orders/14205...,ZIP,NaN,NaN,NaN,NaN
3,https://data.gov.cz/zdroj/datové-sady/70890749...,https://data.gov.cz/zdroj/datové-sady/70890749...,Soubor,Distribuce 1,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://data.gov.cz/podmínky-užití/není-autors...,https://data.gov.cz/podmínky-užití/není-chráně...,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://vys.krajdtm.cz/dmx-server/orders/14205...,ZIP,NaN,NaN,NaN,NaN
4,https://data.gov.cz/zdroj/datové-sady/70890749...,https://data.gov.cz/zdroj/datové-sady/70890749...,Soubor,Distribuce 1,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://data.gov.cz/podmínky-užití/není-autors...,https://data.gov.cz/podmínky-užití/není-chráně...,https://data.gov.cz/podmínky-užití/neobsahuje-...,https://vys.krajdtm.cz/dmx-server/orders/14205...,ZIP,NaN,NaN,NaN,NaN